# Description

This notebook will serve to test ideas before implementation

In [14]:
using LinearAlgebra
A = exp(diagm(-[1, -1.0im]))
B = [1;0.0]
A[1, :]

2-element Vector{ComplexF64}:
 0.36787944117144233 + 0.0im
                 0.0 + 0.0im

In [6]:
using LegendrePolynomials

collectPl.([0.1, 0.5], lmax = 5)

zeros((3, 2)) .+ 2

3×2 Matrix{Float64}:
 2.0  2.0
 2.0  2.0
 2.0  2.0

In [13]:
function A2(a; b = 2*a)
    return a + b
end


A2(2)

6

In [31]:
using LegendrePolynomials, OffsetArrays

A = collectPl(0.5, lmax = 5)
amplitudes = [0.0, 1, 2, 3, 4, 5];


function broadcast(f::Any, amplitudes::Vector{Float64}, A::T) where T <: OffsetArrays.OffsetArray 
    result = fill(0.0, length(amplitudes));
    for (ii, jj) in zip(eachindex(amplitudes), eachindex(A))
        result[ii] = f(amplitudes[ii], A[jj]); 
    end

    return result
end


.+(amplitudes::Vector{Floag64}, A::T) where T <: OffsetArrays.OffsetArray = broadcast(+, amplitudes, A)

amplitudes .+ A

ErrorException: syntax: invalid function name ".+" around d:\GITRepos\km-dropplet-solidsubstrate\julia\1_code\playground.ipynb:17

In [33]:
using OffsetArrays
typeof(A) <: OffsetArrays.OffsetArray


for (ii, jj) in zip(A, A)
    println("$ii, $jj")
end 


1.0, 1.0
0.5, 0.5
-0.125, -0.125
-0.4375, -0.4375
-0.2890625, -0.2890625
0.08984375, 0.08984375


In [13]:
using LegendrePolynomials
import LegendrePolynomials: collectPl
LegendrePolys(x::Float64; lmax::Integer) = parent(collectPl(x, lmax = lmax))
#Int64 <: Integer
C = LegendrePolys.(0.5, lmax = 5); amplitudes = [0.0, 1, 2, 3, 4, 5];;
amplitudes .* C

6-element Vector{Float64}:
  0.0
  0.5
 -0.25
 -1.3125
 -1.15625
  0.44921875

In [55]:
LegendrePolys(x::Float64; lmax::Integer) = (collectPl(x, lmax = lmax)).parent


#collectPl.(0.1, lmax = 1).parent .* collectPl.(0.1, lmax = 1).parent
@. collectPl(0.1, lmax = 1).parent * collectPl(0.1, lmax=1).parent



2-element Vector{Float64}:
 1.0
 0.010000000000000002

In [83]:
B = 0:0.1:1
convert(Array{Float64}, B)

11-element Vector{Float64}:
 0.0
 0.1
 0.2
 0.3
 0.4
 0.5
 0.6
 0.7
 0.8
 0.9
 1.0

In [49]:
using LegendrePolynomials

B = collectPl.(0.1, lmax = 5).parent
LP(x::Float64; lmax::Integer) = (collectPl(x, lmax = lmax).parent)
C = LP(0.1, lmax =5)
#(LP.(0.1, lmax = 5)) .* (LP.(0.1, lmax = 5))
A = [0.1, 0.2]
@. (collectPl(A, lmax = 5).parent) + (collectPl(A, lmax = 5).parent)



ErrorException: type Array has no field parent

In [57]:
include("./theta_from_cylindrical.jl")
theta_from_cylindrical(0.1, [0, 0])

0.10016742111643213